// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func footer() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-center\"><p class=\"text-xl font-bold\">\"Понедельник\" уже настал;) <br>Записывайся на ознакомительную консультацию</p></div><footer class=\"footer items-center p-4\"><aside class=\"items-center grid-flow-col\"><svg height=\"20\" width=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\" xml:space=\"preserve\"><path d=\"M476.886 337.609c-29.533-29.533-72.785-37.15-109.422-22.902l-53.474-53.474 145.25-145.25c32.028-32.028 32.028-83.954 0-115.981L256 203.242 52.759 0c-32.026 32.028-32.026 83.954 0 115.981l145.25 145.25-53.474 53.474c-36.636-14.248-79.889-6.631-109.422 22.902-39.841 39.843-39.841 104.668 0 144.511 39.843 39.843 104.668 39.843 144.511 0 36.303-36.303 39.512-93.344 9.656-133.334l66.721-66.721 66.721 66.721c-29.856 39.987-26.648 97.029 9.655 133.334 39.843 39.843 104.668 39.843 144.511 0 39.84-39.841 39.84-104.668-.002-144.509zM140.212 442.706c-18.109 18.111-47.577 18.111-65.686 0-18.111-18.109-18.111-47.577 0-65.686 18.109-18.111 47.577-18.111 65.686 0 18.11 18.109 18.11 47.577 0 65.686zm297.262 0c-18.109 18.111-47.577 18.111-65.686 0-18.111-18.109-18.111-47.577 0-65.686 18.109-18.111 47.577-18.111 65.686 0 18.111 18.109 18.111 47.577 0 65.686z\"></path></svg><p>by <a class=\"link link-secondary font-bold\" target=\"_blank\" href=\"https://github.com/hyperpuncher\">igor</a></p></aside></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
