// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func price() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"overflow-x-auto\"><table class=\"table table-sm table-zebra sm:table-lg\"><thead class=\"lg:text-base\"><tr><th>Услуга</th><th>Время</th><th>Занятия</th><th>Цена BYN</th></tr></thead> <tbody><tr><td>Ознакомительная консультация</td><td>30</td><td>1</td><td>0</td></tr><tr><td>Общий английский индивидуальное занятие</td><td>60</td><td>4</td><td>280</td></tr><tr><td>Общий английский парное занятие</td><td>60</td><td>4</td><td>200</td></tr><tr><td>Бизнес английский индивидуальное занятие</td><td>60</td><td>4</td><td>280</td></tr><tr><td>Бизнес английский парное занятие</td><td>60</td><td>4</td><td>200</td></tr><tr><td>Подготовка к собеседованию индивидуальное занятие</td><td>60</td><td>4</td><td>280</td></tr><tr><td>Разговорный киноклуб (4/6 человек)</td><td>90</td><td>1</td><td>35</td></tr></tbody></table></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
