// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func price() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"overflow-x-auto\"><table class=\"table table-lg table-zebra\"><thead><tr><th>Услуга</th><th>Занятия</th><th>Цена BYN</th></tr></thead> <tbody><tr><td>Ознакомительная консультация 30 минут</td><td>1</td><td>0</td></tr><tr><td>Общий английский индивидуальное занятие 60 минут</td><td>4</td><td>260</td></tr><tr><td>Общий английский парное занятие 60 минут</td><td>4</td><td>200</td></tr><tr><td>Бизнес английский индивидуальное занятие 60 минут</td><td>4</td><td>260</td></tr><tr><td>Бизнес английский парное занятие 60 минут</td><td>4</td><td>200</td></tr><tr><td>Подготовка к собеседованию индивидуальное занятие</td><td>4</td><td>260</td></tr><tr><td>Разговорный киноклуб (4/6 человек) 90 минут</td><td>1</td><td>25</td></tr></tbody></table></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
